# Generated by Django 3.1.1 on 2020-09-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='option',
            field=models.CharField(choices=[('FILE', 'file'), ('FOLDER', 'folder')], default='FILE', max_length=6),
        ),
    ]
